### ISSUE TITLE
Instructions should be more vehement about not using 'sudo' to run bundle.

### ISSUE THREAD

**Issue by elijah** [pivotal-sprout/sprout-wrap#52]
I hit the issue where home-brew couldn't be properly detected too, and I think the source of confusion on my part was bullet point "4" of README.md.

It says "you shouldn't sudo bundle if you're running under rbenv" -- but as a new user of sprout-wrap, I don't KNOW that one of the things that's going to happen is that my pristine mac is going to have rbenv and rubymine installed on it.

I got myself into a pickle where I was picking up the wrong ruby - because I had gotten sufficiently far into the soloist exec that the ruby had changed, I think.

I had to eventually blow away my sprout-wrap working copy, clone a new one, and go from there.  It worked, once I figured out that I had screwed up a bit and was interacting with an interpreter other than what I expected.

Instructions should be made more specific -- do not run 'sudo bundle' unless you know what you're doing.  And, in general, err on the side of caution -- if something doesn't NEED sudo, _don't use it_.  :)

**Comment by cjcjameson** [comment]
We ran into the same issue; the docs are still not vehement enough about not using sudo and it seems whatever happened in issue #51 didn't remove sudo from the README. Is there a way to get around the chicken & egg problem without sudo? Installing rbenv or rvm separately?

**Comment by hiremaga** [comment]
Thanks @cjcjameson, I've removed the sudo from the README again (3cf5c6bce).

The solution to the chicken and egg problem is to always use system ruby. This should change with Rbenv or RVM since the a [.ruby-version file in the sprout-wrap](https://github.com/pivotal-sprout/sprout-wrap/blob/master/.ruby-version) refers to system ruby.
