### ISSUE TITLE
Create a bootstrap script

### ISSUE THREAD

**Issue by bobbrez** [pivotal-sprout/sprout-wrap#54]
It would really helpful if a script like the one for [Boxen Web] (https://github.com/boxen/boxen-web/blob/59d12a06c50ee441208f6515cf8149faa1b824dc/app/views/splash/script.sh.erb) existed so that a user could kickstart the process similar to how Boxen (via Boxen Web) or Homebrew works with just executing a cURL'ed script.

**Comment by hiremaga** [comment]
Close this due since its pretty stale at this point.
