### ISSUE TITLE
Unable to update fonts

### ISSUE THREAD

**Issue by AndreasMaier** [pivotal-sprout/sprout-wrap#65]
sprout-wrap crashes for me in sprout-terminal's update_font with a message that it cannot get 'http://cheffiles.pivotallabs.com/MenloRegular18pt.bin' via the remote_file method.

**Comment by aramprice** [comment]
@hiremaga - I think this domain (and bucket?) may have been removed by IT.

Perhaps we should remove the recipe in question?

**Comment by hiremaga** [comment]
This recipe has already been removed. I'd suggest updating (librarian-chef
update sprout-terminal) to the latest sprout-terminal sha and removing any
references to this recipe.

**Comment by hiremaga** [comment]
Actually, it looks like I forgot to update sprout-terminal for sprout-wrap when removing the reference to update_fonts. I'm just about to do this.

**Comment by hiremaga** [comment]
Just pushed 3f3d97f4, @AndreasMaier does this work for you?
