### ISSUE TITLE
Rename this repo to developer-workstation or pivotal-developer-workstation

### ISSUE THREAD

**Issue by spilth** [pivotal-sprout/sprout-wrap#82]
So that people can easily find it and understand what it is for.

**Comment by hiremaga** [comment]
Thanks for pointing this out @spilth. I agree that a different name might better convey this repo's purpose.

In the past this project has tried to be 2 things:
1. A description for a universal Pivotal Labs developer image (I think this goal is no longer realistic or true)
2. A living example of how to compose Sprout's various cookbooks/recipes into a description of a team's workstation

I think something along lines of pivotal-sprout/workstation-ruby or pivotal-sprout/workstation-java might be interesting. Both of these better convey the purpose of the repo while keeping its scope immediately useful to a subset of Sprout's users. Perhaps in time, and with enough interest, there might even be room for more than one workstation-* repo.

**Comment by aramprice** [comment]
Maybe in keeping with a convention some teams have come up with (`sprout-<team-name>`) we could change this to `sprout-pivotal(-workstation)`. If people want to specialize maybe point them at something like `sprout-exemplar`?

**Comment by hiremaga** [comment]
The sprout prefix is good for sprout's cookbooks, it might be okay to break
from that for this repo. It might even help it standout.

Perhaps something like pivotal-workstation-ruby to make room for
pivotal-workstation-java, pivotal-workstation-ios etc.

**Comment by aramprice** [comment]
Sounds reasonable to me.
