### ISSUE TITLE
flycut prompts for sudo password suspiciously frequently

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-wrap#88]
On a fresh install, brew installing flycut seems to always prompt for a password. Why flycut? It's pretty annoying to walk away from your computer, wait a while, and come back to see that password prompt.

**Comment by aramprice** [comment]
fwiw I have not seen this yet and have been using on El Cap machines with flycut installed via sprout (via brew).

**Comment by hiremaga** [comment]
Never seen this. Can this be reproduced reliably on a vanilla workstation?

**Comment by wendorf** [comment]
I just got this again today running a standard sprout-wrap on a newly provided machine. Except, this time (as I've experienced multiple times in the past) it just failed because "no tty present" and I had to re-run `bundle exec soloist` to have success.

**Comment by ljfranklin** [comment]
Just saw this as well on clean El Capitan install. Like @wendorf, running `soloist` again with no changes worked fine. Here's the error to help Google searchers:

```
    ---- Begin output of /usr/local/bin/brew cask install flycut  ----
    STDOUT: ==> Downloading https://github.com/downloads/TermiT/Flycut/flycut1.5.pkg
    ==> Verifying checksum for Cask flycut
    ==> Running installer for flycut; your password may be necessary.
    ==> Package installers may write to any location; options such as --appdir are ignored.
    ==> sudo: no tty present and no askpass program specified
    STDERR: Error: Command failed to execute!

    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/flycut/1.5/flycut1.5.pkg>", "-target", "/", "-allowUntrusted"]
```

**Comment by wendorf** [comment]
I just got this on a customized sprout-wrap soloistrc when doing a brew cask install of google-hangouts. Maybe points to this being a timing issue of sudo timing out?

**Comment by aramprice** [comment]
Going to archive this repo, closing.
