### ISSUE TITLE
chef 12.9.x doesn't support system ruby

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-wrap#90]
chef 12.9.38 was released today, and drops support for Ruby 2.0.x, which means that El Capitan's system ruby won't work.

This also means that all of our cookbooks that don't have a Gemfile.lock will start failing. @hiremaga @aramprice have any thoughts about this? My first idea is a pivotal-sprout gem that is nothing but a gemspec to keep us on chef 12.8.x.

**Comment by aramprice** [comment]
A lighter weight version of this might be to put this into sprout-exemplar Gemfile.

Having a pivotal-sprout gem could be a good shim... but maybe we should just make a PR to soloist?

aram

**Comment by aramprice** [comment]
^^ FYI @mkocher

**Comment by hiremaga** [comment]
I think we should lock this in soloist since it's used pretty much
exclusively for sprout at this point.

@mkocher would you be open to giving @danwendorf commit privileges to
soloist for this kind of thing?

**Comment by mkocher** [comment]
@hiremaga @wendorf Done.

**Comment by hiremaga** [comment]
Thanks!

@wendorf @aramprice, is one of you able to make that change/PR to soloist?

**Comment by aramprice** [comment]
I did a little more testing and it looks like [`chef-zero`](https://github.com/chef/chef-zero/commit/9c3a06b1ec82310b8ec817968d27c381188a0d53) no longer supports ruby 2.0

I suspect that this commit comes after actual support was removed.

With some experimentation I found that I was only able to successfully install on El Capitan with the following restriction in my Gemfile:

```ruby
gem 'chef-zero', '< 4.5'
```

**Comment by wendorf** [comment]
Thanks @mkocher for the access.

@aramprice @hiremaga I have a passing build of soloist at https://travis-ci.org/wendorf/soloist/builds/123516316 and it just needs a little bit of cleanup before pushing out a new version.

**Comment by wendorf** [comment]
We can close this issue once mkocher/soloist#39 is completed.

**Comment by aramprice** [comment]
See also https://github.com/pivotal-sprout/sprout-wrap/issues/99

**Comment by aramprice** [comment]
Going to archive this repo, closing.
