### ISSUE TITLE
Can't install Nokogiri because of libxml2 dependency

### ISSUE THREAD

**Issue by ClayShentrup** [pivotal-sprout/sprout-wrap#91]
I get this error.

```bash
Installing nokogiri 1.6.7.2 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

**Comment by aramprice** [comment]
Some experimentation may be necessary for your particular setup but recently I have been able to successfully install the latest nokogiri on OS X 10.11 (El Cap) plus AppStore install Xcode. No `homebrew` libraries were necessary. Using only the Xcode CLI tools was not sufficient.

**Comment by ClayShentrup** [comment]
Thanks @aramprice. I changed my shell from zsh back to bash and it worked for reasons that aren't immediately obvious to me.

**Comment by wendorf** [comment]
Hi @ClayShentrup ,

Thanks for following up—I'm glad things are working for you. I'd like to keep this issue open as a note to look at running sprout on zsh. As long as bash is available, there's no reason immediately obvious to me why sprout-wrap should not be able to be executed from zsh.

Do you know if anything else in your environment changed from the failed run to the successful run? Did you upgrade any rubies and/or gems?

**Comment by ClayShentrup** [comment]
@wendorf I'll get back to you on this as soon as possible. Thanks.

**Comment by ClayShentrup** [comment]
@wendorf I've reinstalled oh-my-zsh but the installation still succeeds. I unfortunately don't know what might have changed. Thanks for your concern and I'm sorry I couldn't be more helpful.
