### ISSUE TITLE
Default to chruby

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-wrap#93]
This is a request for opinions. In my understanding, people are now preferring chruby over rbenv, and I would like to make our defaults better.

Additionally, it looks like the rbenv cookbook may not be working as well as we'd like: pivotal-sprout/sprout-rbenv#6

Thoughts?

**Comment by aramprice** [comment]
I'm in favor but then again I've been using chruby for a while...

**Comment by aramprice** [comment]
Going to archive this repo, closing.
