### ISSUE TITLE
Some newer versions of OS X seem to have problems mounting disk images, causing Travis build failures

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-wrap#94]
See the failure at https://travis-ci.org/pivotal-sprout/sprout-wrap/builds/134004962

Error message when trying to `brew cask install firefox`:

```
hdiutil: mount failed - Protocol wrong type for socket
STDERR: Error: Empty plist input
```

This is resolved by _not_ performing a `systemupdate`.

There is some conversation about the issue, but it's not clear what we can do in the Travis world to fix it:
http://apple.stackexchange.com/questions/238771/i-cannot-mount-dmg-file-for-vmware-fusion-protocol-wrong-type-for-socket-error
https://origin-discussions-us.apple.com/thread/7568956

Is this just a problem in Travis, or will people see the issue in real life?

**Comment by aramprice** [comment]
Going to archive this repo, closing.
