### ISSUE TITLE
Add `reload` to end of ./sprout script

### ISSUE THREAD

**Issue by ardnaxelarak** [pivotal-sprout/sprout-wrap#96]
This would save the effort of having to reload if any changes were made to aliases or bash_it functions.

**Comment by wendorf** [comment]
I think something like http://madebynathan.com/2012/10/29/auto-reloading-your-bashrc/ would work, but there's a chicken-and-the-egg problem. The first time you run Sprout, you still won't have this and will need to manually reload. Thoughts?

**Comment by aramprice** [comment]
This feels fragile/excessive, [43 lines](https://github.com/ndbroadbent/dotfiles/blob/master/bashrc/auto_reload.sh) that could go wrong.

Maybe just document some options:
- "At this point you should open a new shell/terminal to see any updates to your `bash` environment"
- "You can run `exec bash -l` to see any updates to your `bash` environment"
  - maybe this could be added to `./sprout`

I'm a little worried about auto-reloading a user into a broken shell environment. The recovery path isn't obvious.

**Comment by aramprice** [comment]
Going to archive this repo, closing.
